const palettes = [
    {   name: 'Window Tide',
        colors: [
            {   name: 'Midnight Blue',
                hex: '#41729F',
                class: 'window-tide__color_midnight-blue',
                bgClass: 'window-tide__background_midnight-blue',
            },
            {   name: 'Blue Gray',
                hex: '#5885AF',
                class: 'window-tide__color_blue-gray',
                bgClass: 'window-tide__background_blue-gray',
            },
            {   name: 'Dark Blue',
                hex: '#274472',
                class: 'window-tide__color_dark-blue',
                bgClass: 'window-tide__background_dark-blue',
            },
            {   name: 'Baby Blue',
                hex: '#C3E0E5',
                class: 'window-tide__color_baby-blue',
                bgClass: 'window-tide__background_baby-blue',
            },
        ],
        bodyColor: 'whitesmoke',
        darkColor: '#274472',
        lightColor: '#5885AF',
    },
    {   name: 'Retro Punch',
        colors: [
            {   name: 'Cyan',
                hex: '#2FF3E0',
                class: 'retro-punch__color_cyan',
                bgClass: 'retro-punch__background_cyan',
            },
            {   name: 'Gold',
                hex: '#F8D210',
                class: 'retro-punch__color_gold',
                bgClass: 'retro-punch__background_gold',
            },
            {   name: 'Pink',
                hex: '#FA26A0',
                class: 'retro-punch__color_pink',
                bgClass: 'retro-punch__background_pink',
            },
            {   name: 'Red',
                hex: '#F51720',
                class: 'retro-punch__color_red',
                bgClass: 'retro-punch__background_red',
            },
        ],
        bodyColor: 'whitesmoke',
        darkColor: '#274472',
        lightColor: '#5885AF',
    },
    {   name: 'Bold Geometry',
        colors: [
            {   name: 'Light Blue',
                hex: '#0D698B',
                class: 'bold-geometry__color_light-blue',
                bgClass: 'bold-geometry__background_light-blue',
            },
            {   name: 'Ivory',
                hex: '#F2F1E8',
                class: 'bold-geometry__color_ivory',
                bgClass: 'bold-geometry__background_ivory',
            },
            {   name: 'Dark Blue',
                hex: '#050533',
                class: 'bold-geometry__color_dark-blue',
                bgClass: 'bold-geometry__background_dark-blue',
            },
            {   name: 'Red',
                hex: '#E34234',
                class: 'bold-geometry__color_red',
                bgClass: 'bold-geometry__background_red',
            },
        ],
        bodyColor: 'whitesmoke',
        darkColor: '#274472',
        lightColor: '#5885AF',
    },
    // {   name: 'Teenage Pop',
    //     colors: [
    //         {   name: 'Aqua',
    //             hex: '#71E7E0',
    //             class: 'teenage-pop__color_aqua',
    //             bgClass: 'teenage-pop__background_aqua',
    //         },
    //         {   name: 'Pink',
    //             hex: '#FF8BDA',
    //             class: 'teenage-pop__color_pink',
    //             bgClass: 'teenage-pop__background_pink',
    //         },
    //         {   name: 'Blue',
    //             hex: '#43A9DD',
    //             class: 'teenage-pop__color_blue',
    //             bgClass: 'teenage-pop__background_blue',
    //         },
    //         {   name: 'Fuchsia',
    //             hex: '#F12E90',
    //             class: 'teenage-pop__color_fuchsia',
    //             bgClass: 'teenage-pop__background_fuchsia',
    //         },
    //     ],
    //     bodyColor: 'whitesmoke',
    //     darkColor: '#F12E90',
    //     lightColor: '#43A9DD',
    // },

    
]

export default palettes